"""timestamp to user_programs

Revision ID: 23be2459cc5f
Revises: 2c5b6c0cde70
Create Date: 2020-06-22 17:21:47.437640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23be2459cc5f'
down_revision = '2c5b6c0cde70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_programs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_programs_timestamp'), 'users_programs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_programs_timestamp'), table_name='users_programs')
    op.drop_column('users_programs', 'timestamp')
    # ### end Alembic commands ###
