"""pledge table

Revision ID: 707209cb7c9a
Revises: 2608880f0a05
Create Date: 2020-07-12 18:52:46.789855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707209cb7c9a'
down_revision = '2608880f0a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pledge_timestamp'), 'pledge', ['timestamp'], unique=False)
    op.create_table('pledges',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pledge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pledges')
    op.drop_index(op.f('ix_pledge_timestamp'), table_name='pledge')
    op.drop_table('pledge')
    # ### end Alembic commands ###
